# Lightweight version of docker-compose for systems with limited resources
services:
  # PostgreSQL Database 
  db:
    image: postgres:13-alpine
    environment:
      POSTGRES_DB: echelon
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U postgres"]
      interval: 10s
      timeout: 5s
      retries: 5
    deploy:
      resources:
        limits:
          memory: 300M
          
  # Adminer for database management (lightweight alternative to full backend)
  adminer:
    image: adminer:4.8.1
    restart: always
    depends_on:
      - db
    ports:
      - "8080:8080"
    deploy:
      resources:
        limits:
          memory: 100M
          
volumes:
  postgres_data: